on:
  push:
    branches:
      - master
name: Build and Release APK & IPA
jobs:
  build-ios:
    name: Build Flutter (iOS)
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
      - name: Install pub Dependencies
        run: flutter pub get
      - name: Clean flutter project
        run: flutter clean
      - name: Build iOS App
        run: flutter build ios --release --no-codesign
      - name: Upload IPA
        uses: actions/upload-artifact@v2
        with:
          name: ios-build
          path: build/ios/iphoneos
  build-android:
    name: Build Flutter (Android)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name : Output keystore to CI environment
        run: echo $SIGNING_KEY | base64 -d > android/app/key.jks
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
      - name: Install pub Dependencies
        run: flutter pub get
      - name: Clean flutter project
        run: flutter clean
      - name: Build Android App
        run: flutter build appbundle
        env:
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS: ${{ secrets.ALIAS }}
          KEY_PATH: key.jks
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: android-build
          path: build/app/outputs/bundle/release
  beta-ios:
    name: Upload iOS Beta to Firebase App Distribution
    needs: [build-ios]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ios-build
      - name: Upload IPA
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.2
        with:
          appId: ${{ secrets.FIREBASE_IOS_APPID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          group: testers
          file: Runner.ipa
  beta_android:
    name: Upload Android Beta to Firebase App Distribution
    needs: [build-android]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: android-build
      - name: Upload APK
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.2
        with:
          appId: ${{ secrets.FIREBASE_IOS_APPID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          group: testers
          file: app-release.aap
