on:
  push:
    branches:
      - master
name: Build and Release APK & IPA
jobs:
  build:
    name: Build Apps
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name : Output keystore to CI environment
        run: echo $SIGNING_KEY | base64 -d > android/app/key.jks
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
      - name: Install pub Dependencies
        run:
          flutter pub get
          flutter clean
      - name: Build Android App
        run: flutter build appbundle
        env:
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS: ${{ secrets.ALIAS }}
          KEY_PATH: key.jks
      - name: Build iOS App
        run:
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - name: Create a Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/bundle/release/app.aab,build/ios/iphoneos/app.ipa"
          tag: v${{ secrets.MAJOR }}.${{ secrets.MINOR }}-droid-${{ github.sha }}
          token: ${{ secrets.TOKEN }}
