on:
  pull_request:
    branches:
      - master
      - tester
      - developer
name: Run checks (APK & IPA)
jobs:
  build_android:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
    - run: flutter pub get
    - run: flutter build apk --debug --split-per-abi
  build_ios:
    name: Build IPA
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - run: flutter pub get
      - run: flutter build ios --debug --no-codesign
